alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: k-8-sacademy-hello
region: tor
services:
- http_port: 80
  image:
    registry: k8sacademy
    registry_type: DOCKER_HUB
    repository: hello
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xs
  name: k-8-sacademy-hello
  routes:
  - path: /
  source_dir: /
- internal_ports: 
    - 80
  image:
    registry: k8sacademy
    registry_type: DOCKER_HUB
    repository: hello
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xs
  name: hello-backend
  source_dir: /

