apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: do-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 10Gi
